service: nest-aws

provider: 
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1


functions: 
  hello: 
    handler: src/lambda/helloworld.handler
    events: 
      - http: 
          path: nest-aws/hello
          method: get


plugins: 
  - serverless-plugin-typescript
  - serverless-offline